### ISSUE TITLE
Unsupported source map comment

### ISSUE THREAD

**Issue by AlCalzone** [egoist/esbuild-register#11]
I'm getting a ton of these when running scripts with esbuild-register:
```
{
  column: 21,
  file: 'C:\\Repositories\\node-zwave-js\\packages\\core\\build\\index.js',
  length: 12,
  line: 32,
  lineText: '//# sourceMappingURL=index.js.map',
  namespace: ''
}
Unsupported source map comment
{
  column: 21,
  file: 'C:\\Repositories\\node-zwave-js\\packages\\core\\build\\capabilities\\CommandClasses.js',
  length: 21,
  line: 245,
  lineText: '//# sourceMappingURL=CommandClasses.js.map',
  namespace: ''
}
Unsupported source map comment
{
  column: 21,
  file: 'C:\\Repositories\\node-zwave-js\\packages\\shared\\build\\index.js',
  length: 12,
  line: 21,
  lineText: '//# sourceMappingURL=index.js.map',
  namespace: ''
}
```
Any idea what I can do?

**Comment by natew** [comment]
Getting this too, if you change `sourcemap: 'both'` to false in dist/node.js you can patch for now to disable sourcemaps but not get the errors.

**Comment by jinjor** [comment]
This message seems to come from this line in esbuild:
https://github.com/evanw/esbuild/blob/c5a88a04561debf302243b0afd11d365257a2373/internal/bundler/bundler.go#L551

In my case, rebuilding the local package with `"inlineSourceMap": true` (in `tsconfig.json`) solved the problem.

**Comment by AlCalzone** [comment]
See https://github.com/evanw/esbuild/issues/1358#issuecomment-857016579 - `esbuild-register` uses the `transformSync` API which does not do path resolution. If it used the `buildSync` API instead it could support the external source maps.
