### ISSUE TITLE
tsconfig.json may contain comma-dangle

### ISSUE THREAD

**Issue by Shigma** [egoist/esbuild-register#2]
tsconfig.json may contain comma-dangle which is not supported by current implementation.

**Comment by skyrpex** [comment]
Maybe it would be better to rely on a jsonc parser rather than just stripping the comments?

**Comment by privatenumber** [comment]
It's probably no longer an issue, but wanted to share that TIL you can leverage TS to read the config to get the exact same parsing behavior:
```js
const ts = require('typescript');

console.log(ts.readConfigFile('tsconfig.json', ts.sys.readFile));
```
