### ISSUE TITLE
Why slower than esbuild-runner?

### ISSUE THREAD

**Issue by IlyaSemenov** [egoist/esbuild-register#23]
On a middle scale project,

```
node -r esbuild-register -r dotenv/config -r tsconfig-paths/register src/api/server.ts
```

takes ~8 seconds to start.

```
node -r esbuild-runner/register -r dotenv/config -r tsconfig-paths/register src/api/server.ts
```

takes ~1 second to start.

How come? I even tried upgrading to the latest esbuild 0.12.3 (with yarn resolutions), it made no difference to either project.

I don't like that esbuild-runner seems to be abandoned, but I don't like the 8x difference in speed either.

**Comment by Maiquu** [comment]
I'm assuming `esbuild-register` is trying to compile one of your modules located in `node_modules`. For my case, `lodash-es` was the culprit. Entire `lodash-es` module was getting compiled which slowed down startup quite a lot.

**Comment by IlyaSemenov** [comment]
esbuild-runner is no more abandoned so I'm inclined to close this. I don't have a ready made reproducible case, after all.
