### ISSUE TITLE
set  "type": "module" in  `package.json` breaks the build

### ISSUE THREAD

**Issue by yaquawa** [egoist/esbuild-register#26]
It'll get this error if you set the "type": "module" in  the `package.json`
```
node -r esbuild-register scripts/test.ts
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /scripts/test.ts
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:65:15)
    at Loader.getFormat (internal/modules/esm/loader.js:101:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:31)
    at Loader.import (internal/modules/esm/loader.js:164:17)
    at Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

**Comment by gunters63** [comment]
I have the same problem.

The exception comes from here: https://github1s.com/nodejs/node/blob/HEAD/lib/internal/modules/esm/get_format.js

Unfortunately it seems to be hardwired for Node in module mode to reject file extension `.ts`.

Maybe it is possible to patch the file name before it is passed to Node?

**Comment by Azure64933** [comment]
I have the same problem, too.

However, I find out that I don`t name my js project as  **.js**
(I compile my project on VSCode, it will allow you to compile your file  without define project type)

**Comment by danny-andrews** [comment]
I'm getting the same issue. Unfortunately, I don't think it can be fixed without using node's experimental [loaders](https://nodejs.org/api/esm.html#loaders) feature as es6 modules only support `.js` and `.jsx` extensions by default.

**Comment by egoist** [comment]
well, this a temporary workaround (better than crashing): it compiles the code to cjs, you can't import esm-only module in this way tho.

**Comment by egoist** [comment]
not actually fixed, but now you can create an intermediate  `test.cjs` file to `require('./test.ts')` and run `node -r esbuild-register scripts/test.cjs`

**Comment by egoist** [comment]
the correct solution is like @danny-andrews said using --experimental-loader, PR welcome

**Comment by KoichiKiyokawa** [comment]
One workaround is to make a small package.json and set `"type": "commonjs"`

For example, when you run `node -r esbuild-register scripts/test.ts`,

```
scripts
├── package.json // <-- new
└── test.ts
```

```json5
// scripts/package.json
{
  "//": "https://github.com/egoist/esbuild-register/issues/26",
  "type": "commonjs"
}
```

**Comment by Savid** [comment]
I've just been playing with ES modules recently and I've had some success with the suggestion from @danny-andrews;

`esbuild-register-loader.mjs`
```js
const extensionsRegex = /\.ts$|\.tsx$/;

export async function load(url, context, defaultLoad) {
  if (extensionsRegex.test(url)) {
    const { source } = await defaultLoad(url, { format: 'module' });
    return {
      format: 'commonjs',
      source: source,
    };
  }
  // let Node.js handle all other URLs
  return defaultLoad(url, context, defaultLoad);
}
```

then run;
```bash
node --experimental-loader ./esbuild-register-loader.mjs -r esbuild-register scripts/test.ts
```

**Comment by egoist** [comment]
Thanks to @Savid 's comment, this was added in 3.4.0 : https://github.com/egoist/esbuild-register#experimental-loader-support

**Comment by AlexBlokh** [comment]
@Savid @egoist is there a way I can load `.ts` this way, but with esm support? particularly for top-level await
I've used @esbuild-kit/esm-loader, but it increase start time x6 times

the solution above works, but doesn't let me have esm supported features, since it bundles to cjs

replacing format to `esm` gives this error `Unknown module format: esm for URL file://.../file.ts`

**Comment by AlexBlokh** [comment]
well, I don't know how, but when you do that
```ts
const extensionsRegex = /\.(ts|tsx|mts|cts)$/

export async function load(url, context, defaultLoad) {
  if (extensionsRegex.test(url)) {
    const { source } = await defaultLoad(url, { ...context, format: 'module' })
    return {
      ...context,
      source: source,
    }
  }
  // let Node.js handle all other URLs
  return defaultLoad(url, context, defaultLoad)
}
```

it works perfectly
