### ISSUE TITLE
Any ideas to allow passing configuration?

### ISSUE THREAD

**Issue by skyrpex** [egoist/esbuild-register#3]
I specifically mean the `loader` configuration option. In my case, I care about it because the following file doesn't compile with `tsx` (but it does with `ts`):

```ts
// Basically, templated arrow functions are treated as TSX components rather than a templated argument.
const method = <T>() => {
    console.log("hello");
};
```

So maybe... what if we had a `esbuild.config.js(on)` file and read from it, like many other tools?

**Comment by skyrpex** [comment]
BTW, a work around is to transform the code to the following:

```ts
const method = function <T>() {
    console.log("hello");
};
```

**Comment by jsmith** [comment]
Could the `compile` function just check if the extension is `.ts` or `.tsx` and then pass in the correct loader accordingly? Here is a kinda naive approach (that works):
```typescript
loader: path.basename(filename).substr(path.basename(filename).lastIndexOf(".") + 1),
```

 See [node.ts#L34](https://github.com/egoist/esbuild-register/blob/master/src/node.ts#L34)

**Comment by skyrpex** [comment]
I think that would be much better, yeah!

**Comment by jsmith** [comment]
I did not know about that function, thanks for cleaning it up!

**Comment by skyrpex** [comment]
@egoist if you could please have a look! :pray:
