### ISSUE TITLE
Allow programmatic enabling and disabling of `esbuild-register`

### ISSUE THREAD

**Issue by jensmeindertsma** [egoist/esbuild-register#40]
Hey there!

I'm working on https://github.com/facebook/jest/pull/12041, and I'm implementing `esbuild-register` as an alternative to `ts-node`. I'm running into the problem that `esbuild-register` provides no way to programatically enable and disable it. I need to enable it for just a brief period of time ( 1 require + potential imports in the required file ) and then disable it again.

If you agree this feature should be added, let me know. I'm happy to implement it.

**Comment by egoist** [comment]
PR welcome 👌🏻

**Comment by jensmeindertsma** [comment]
@egoist Opened a PR: https://github.com/egoist/esbuild-register/pull/41
