### ISSUE TITLE
Doesn't work without tsconfig (v3.3.0 regression)

### ISSUE THREAD

**Issue by flytaly** [egoist/esbuild-register#49]
If there is no tsconfig.json file somewhere in the tree  `node -r esbuild-register`  hangs and then throw an error

```
node:path:1166
  join(...args) {
      ^

RangeError: Maximum call stack size exceeded
    at Object.join (node:path:1166:7)
    at walkForTsConfig
```

[Works in 3.2.1](https://imgur.com/61oF7AC)

Noticed it today when esno stopped working for me in some directories.

**Comment by egoist** [comment]
cc @hanayashiki

**Comment by hanayashiki** [comment]
Seems to be a problem with tsconfig-paths...

**Comment by egoist** [comment]
Turns out replacing `loadConfig('.')` with `loadConfig()` or `loadConfig(process.cwd())` fixed it 🥶
